// Generated by scripts/generate-narration.mjs — do not edit by hand.
export const TRANSITION = 20;
export const TOTAL_FRAMES = 4672;
export const SCENES: Record<
  string,
  { duration: number; lines: { from: number; duration: number; text: string }[] }
> = {
  "s1": {
    "duration": 499,
    "lines": [
      {
        "from": 14,
        "duration": 262,
        "text": "I'd like you to meet Susan. Over the years, she has built a substantial stock portfolio."
      },
      {
        "from": 276,
        "duration": 197,
        "text": "She wants those investments to provide her income through retirement."
      }
    ]
  },
  "s2": {
    "duration": 689,
    "lines": [
      {
        "from": 14,
        "duration": 337,
        "text": "After reviewing her income and expenses, she decided a 5.0% annual yield will support her."
      },
      {
        "from": 351,
        "duration": 312,
        "text": "Her portfolio holds 23 stocks — and working out which ones actually help is hard to calculate."
      }
    ]
  },
  "s3": {
    "duration": 323,
    "lines": [
      {
        "from": 14,
        "duration": 283,
        "text": "Finding the stocks that move her toward her goal — and spotting the ones that don't — takes real work."
      }
    ]
  },
  "s4": {
    "duration": 527,
    "lines": [
      {
        "from": 14,
        "duration": 229,
        "text": "Yield Guardian can analyze her portfolio — she simply imports it as a guest."
      },
      {
        "from": 243,
        "duration": 258,
        "text": "It reads the tickers and share counts, then calculates her current portfolio value."
      }
    ]
  },
  "s5": {
    "duration": 356,
    "lines": [
      {
        "from": 14,
        "duration": 316,
        "text": "Personal identifying information is ignored — only the data needed for dividends and yield is used."
      }
    ]
  },
  "s6": {
    "duration": 664,
    "lines": [
      {
        "from": 14,
        "duration": 371,
        "text": "The sample portfolio holds familiar stocks — with one, ABBV, that does not meet the 5.0% goal."
      },
      {
        "from": 385,
        "duration": 253,
        "text": "Yield Guardian flags underperforming stocks against the desired annual yield."
      }
    ]
  },
  "s7": {
    "duration": 585,
    "lines": [
      {
        "from": 14,
        "duration": 257,
        "text": "Click Review Underperformers and a comparison appears, side by side."
      },
      {
        "from": 271,
        "duration": 288,
        "text": "Keep the stock, and you see the dividends expected through year end — or see what an alternative would earn."
      }
    ]
  },
  "s8": {
    "duration": 291,
    "lines": [
      {
        "from": 14,
        "duration": 251,
        "text": "And an explainer shows exactly how those end-of-year dividend numbers are calculated."
      }
    ]
  },
  "s9": {
    "duration": 610,
    "lines": [
      {
        "from": 14,
        "duration": 257,
        "text": "In Guest Analysis Mode, stock names, tickers and share counts stay hidden."
      },
      {
        "from": 271,
        "duration": 313,
        "text": "Choosing Save my portfolio starts account creation, and unlocks the alternatives and the new yield."
      }
    ]
  },
  "s10": {
    "duration": 308,
    "lines": [
      {
        "from": 14,
        "duration": 268,
        "text": "See what your portfolio can earn — try Guest Analysis, or head back to the home screen."
      }
    ]
  }
};
export const ORDER = ["s1","s2","s3","s4","s5","s6","s7","s8","s9","s10"];
